// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_nsddm_TMBExports
#include <TMB.hpp>
#include "ddmTMB.h"
#include "ddm4_getmodes_tmb.hpp"
#include "ddm4_tmb.hpp"
#include "ddm7_getmodes_tmb.hpp"
#include "ddm7_tmb.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "ddm4_getmodes_tmb") {
    return ddm4_getmodes_tmb(this);
  } else if(model == "ddm4_tmb") {
    return ddm4_tmb(this);
  } else if(model == "ddm7_getmodes_tmb") {
    return ddm7_getmodes_tmb(this);
  } else if(model == "ddm7_tmb") {
    return ddm7_tmb(this);
  } else {
    Rf_error("Unknown model.");
  }
  return 0;
}
