// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ddm_chain_rcpp
Rcpp::List ddm_chain_rcpp(const arma::vec& rts, const arma::ivec& xs, const arma::mat& info, const int I, const int K, arma::mat alpha, arma::colvec c_MUa, arma::mat c_SIGa, const arma::colvec& m, const arma::mat& invM, const arma::mat& S0, const int nu0, arma::vec a_d, const int biter, const int burnin, bool use_adapt_dao, const double tau2, const double epsilon, const double pi_mix, const double pi_mix1, const double pi_mix2, const double pi_mix3, const int R, const std::string method, const std::string type_alpha, const std::string type_proposal, const std::string ddm, bool verbose, const int& kmax, const double& delta, bool use_lan, std::string lan_path);
RcppExport SEXP _nsddm_ddm_chain_rcpp(SEXP rtsSEXP, SEXP xsSEXP, SEXP infoSEXP, SEXP ISEXP, SEXP KSEXP, SEXP alphaSEXP, SEXP c_MUaSEXP, SEXP c_SIGaSEXP, SEXP mSEXP, SEXP invMSEXP, SEXP S0SEXP, SEXP nu0SEXP, SEXP a_dSEXP, SEXP biterSEXP, SEXP burninSEXP, SEXP use_adapt_daoSEXP, SEXP tau2SEXP, SEXP epsilonSEXP, SEXP pi_mixSEXP, SEXP pi_mix1SEXP, SEXP pi_mix2SEXP, SEXP pi_mix3SEXP, SEXP RSEXP, SEXP methodSEXP, SEXP type_alphaSEXP, SEXP type_proposalSEXP, SEXP ddmSEXP, SEXP verboseSEXP, SEXP kmaxSEXP, SEXP deltaSEXP, SEXP use_lanSEXP, SEXP lan_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type rts(rtsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type info(infoSEXP);
    Rcpp::traits::input_parameter< const int >::type I(ISEXP);
    Rcpp::traits::input_parameter< const int >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type c_MUa(c_MUaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type c_SIGa(c_SIGaSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type invM(invMSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< const int >::type nu0(nu0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a_d(a_dSEXP);
    Rcpp::traits::input_parameter< const int >::type biter(biterSEXP);
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< bool >::type use_adapt_dao(use_adapt_daoSEXP);
    Rcpp::traits::input_parameter< const double >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< const double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< const double >::type pi_mix(pi_mixSEXP);
    Rcpp::traits::input_parameter< const double >::type pi_mix1(pi_mix1SEXP);
    Rcpp::traits::input_parameter< const double >::type pi_mix2(pi_mix2SEXP);
    Rcpp::traits::input_parameter< const double >::type pi_mix3(pi_mix3SEXP);
    Rcpp::traits::input_parameter< const int >::type R(RSEXP);
    Rcpp::traits::input_parameter< const std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const std::string >::type type_alpha(type_alphaSEXP);
    Rcpp::traits::input_parameter< const std::string >::type type_proposal(type_proposalSEXP);
    Rcpp::traits::input_parameter< const std::string >::type ddm(ddmSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const int& >::type kmax(kmaxSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_lan(use_lanSEXP);
    Rcpp::traits::input_parameter< std::string >::type lan_path(lan_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(ddm_chain_rcpp(rts, xs, info, I, K, alpha, c_MUa, c_SIGa, m, invM, S0, nu0, a_d, biter, burnin, use_adapt_dao, tau2, epsilon, pi_mix, pi_mix1, pi_mix2, pi_mix3, R, method, type_alpha, type_proposal, ddm, verbose, kmax, delta, use_lan, lan_path));
    return rcpp_result_gen;
END_RCPP
}
// ddm4_pdf_export
arma::vec ddm4_pdf_export(const arma::vec& rt, const arma::ivec& x, const double& a, const double& t0, const double& w, const double& z, const double& v, const std::string& type_ddm, const int& kmax, const double& delta);
RcppExport SEXP _nsddm_ddm4_pdf_export(SEXP rtSEXP, SEXP xSEXP, SEXP aSEXP, SEXP t0SEXP, SEXP wSEXP, SEXP zSEXP, SEXP vSEXP, SEXP type_ddmSEXP, SEXP kmaxSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type rt(rtSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< const double& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const double& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const double& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type_ddm(type_ddmSEXP);
    Rcpp::traits::input_parameter< const int& >::type kmax(kmaxSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(ddm4_pdf_export(rt, x, a, t0, w, z, v, type_ddm, kmax, delta));
    return rcpp_result_gen;
END_RCPP
}
// ddm7_pdf_export
arma::vec ddm7_pdf_export(const arma::vec& rt, const arma::ivec& x, const double& a, const double& t0, const double& z, const double& v, const double& sv, const double& sz, const double& st0, const std::string& type_ddm, const int& kmax, const double& delta);
RcppExport SEXP _nsddm_ddm7_pdf_export(SEXP rtSEXP, SEXP xSEXP, SEXP aSEXP, SEXP t0SEXP, SEXP zSEXP, SEXP vSEXP, SEXP svSEXP, SEXP szSEXP, SEXP st0SEXP, SEXP type_ddmSEXP, SEXP kmaxSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type rt(rtSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< const double& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const double& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const double& >::type sv(svSEXP);
    Rcpp::traits::input_parameter< const double& >::type sz(szSEXP);
    Rcpp::traits::input_parameter< const double& >::type st0(st0SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type_ddm(type_ddmSEXP);
    Rcpp::traits::input_parameter< const int& >::type kmax(kmaxSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(ddm7_pdf_export(rt, x, a, t0, z, v, sv, sz, st0, type_ddm, kmax, delta));
    return rcpp_result_gen;
END_RCPP
}
// lan_load_weights_export
void lan_load_weights_export(const std::string& path, const std::string& ddm);
RcppExport SEXP _nsddm_lan_load_weights_export(SEXP pathSEXP, SEXP ddmSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type ddm(ddmSEXP);
    lan_load_weights_export(path, ddm);
    return R_NilValue;
END_RCPP
}
// ddm4_lanll_weights_export
arma::vec ddm4_lanll_weights_export(const arma::vec& rt, const arma::ivec& x, const double& a, const double& t0, const double& z, const double& v);
RcppExport SEXP _nsddm_ddm4_lanll_weights_export(SEXP rtSEXP, SEXP xSEXP, SEXP aSEXP, SEXP t0SEXP, SEXP zSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type rt(rtSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< const double& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const double& >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(ddm4_lanll_weights_export(rt, x, a, t0, z, v));
    return rcpp_result_gen;
END_RCPP
}
// ddm4_lanll_grad_weights_rcpp
Rcpp::List ddm4_lanll_grad_weights_rcpp(const arma::colvec& alpha, const arma::vec& rt, const arma::ivec& xs);
RcppExport SEXP _nsddm_ddm4_lanll_grad_weights_rcpp(SEXP alphaSEXP, SEXP rtSEXP, SEXP xsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type rt(rtSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type xs(xsSEXP);
    rcpp_result_gen = Rcpp::wrap(ddm4_lanll_grad_weights_rcpp(alpha, rt, xs));
    return rcpp_result_gen;
END_RCPP
}
// ddm7_lanll_grad_weights_rcpp
Rcpp::List ddm7_lanll_grad_weights_rcpp(const arma::colvec& alpha, const arma::vec& rt, const arma::ivec& xs);
RcppExport SEXP _nsddm_ddm7_lanll_grad_weights_rcpp(SEXP alphaSEXP, SEXP rtSEXP, SEXP xsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type rt(rtSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type xs(xsSEXP);
    rcpp_result_gen = Rcpp::wrap(ddm7_lanll_grad_weights_rcpp(alpha, rt, xs));
    return rcpp_result_gen;
END_RCPP
}
// ddm_lan_nllfct_gradient_rcpp
Rcpp::List ddm_lan_nllfct_gradient_rcpp(const arma::colvec& alpha, const arma::vec& rt, const arma::ivec& xs, const arma::vec& MU, const arma::mat& SIGMA, const arma::mat& invSIGMA, const std::string ddm);
RcppExport SEXP _nsddm_ddm_lan_nllfct_gradient_rcpp(SEXP alphaSEXP, SEXP rtSEXP, SEXP xsSEXP, SEXP MUSEXP, SEXP SIGMASEXP, SEXP invSIGMASEXP, SEXP ddmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type rt(rtSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type MU(MUSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SIGMA(SIGMASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type invSIGMA(invSIGMASEXP);
    Rcpp::traits::input_parameter< const std::string >::type ddm(ddmSEXP);
    rcpp_result_gen = Rcpp::wrap(ddm_lan_nllfct_gradient_rcpp(alpha, rt, xs, MU, SIGMA, invSIGMA, ddm));
    return rcpp_result_gen;
END_RCPP
}
// ddm4_nllfct_export
double ddm4_nllfct_export(const arma::colvec& alpha, const arma::vec& rt, const arma::ivec& xs, const std::string& type_alpha, const std::string& type_ddm, const int& kmax, const double& delta, bool use_lan);
RcppExport SEXP _nsddm_ddm4_nllfct_export(SEXP alphaSEXP, SEXP rtSEXP, SEXP xsSEXP, SEXP type_alphaSEXP, SEXP type_ddmSEXP, SEXP kmaxSEXP, SEXP deltaSEXP, SEXP use_lanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type rt(rtSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type_alpha(type_alphaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type_ddm(type_ddmSEXP);
    Rcpp::traits::input_parameter< const int& >::type kmax(kmaxSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_lan(use_lanSEXP);
    rcpp_result_gen = Rcpp::wrap(ddm4_nllfct_export(alpha, rt, xs, type_alpha, type_ddm, kmax, delta, use_lan));
    return rcpp_result_gen;
END_RCPP
}
// ddm4_random_llfct_rcpp
double ddm4_random_llfct_rcpp(const arma::colvec& alpha, const arma::vec& rti, const arma::ivec& xsi, const arma::vec& MU, const arma::mat& SIGMA, const std::string& type_alpha, const std::string& type_ddm, const int& kmax, const double& delta, bool use_lan);
RcppExport SEXP _nsddm_ddm4_random_llfct_rcpp(SEXP alphaSEXP, SEXP rtiSEXP, SEXP xsiSEXP, SEXP MUSEXP, SEXP SIGMASEXP, SEXP type_alphaSEXP, SEXP type_ddmSEXP, SEXP kmaxSEXP, SEXP deltaSEXP, SEXP use_lanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type rti(rtiSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type xsi(xsiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type MU(MUSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SIGMA(SIGMASEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type_alpha(type_alphaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type_ddm(type_ddmSEXP);
    Rcpp::traits::input_parameter< const int& >::type kmax(kmaxSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_lan(use_lanSEXP);
    rcpp_result_gen = Rcpp::wrap(ddm4_random_llfct_rcpp(alpha, rti, xsi, MU, SIGMA, type_alpha, type_ddm, kmax, delta, use_lan));
    return rcpp_result_gen;
END_RCPP
}
// ddm4_random_nllfct_rcpp
double ddm4_random_nllfct_rcpp(const arma::colvec& alpha, const arma::vec& rti, const arma::ivec& xsi, const arma::vec& MU, const arma::mat& SIGMA, const std::string& type_alpha, const std::string& type_ddm, const int& kmax, const double& delta, bool use_lan);
RcppExport SEXP _nsddm_ddm4_random_nllfct_rcpp(SEXP alphaSEXP, SEXP rtiSEXP, SEXP xsiSEXP, SEXP MUSEXP, SEXP SIGMASEXP, SEXP type_alphaSEXP, SEXP type_ddmSEXP, SEXP kmaxSEXP, SEXP deltaSEXP, SEXP use_lanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type rti(rtiSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type xsi(xsiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type MU(MUSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SIGMA(SIGMASEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type_alpha(type_alphaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type_ddm(type_ddmSEXP);
    Rcpp::traits::input_parameter< const int& >::type kmax(kmaxSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_lan(use_lanSEXP);
    rcpp_result_gen = Rcpp::wrap(ddm4_random_nllfct_rcpp(alpha, rti, xsi, MU, SIGMA, type_alpha, type_ddm, kmax, delta, use_lan));
    return rcpp_result_gen;
END_RCPP
}
// ddm7_nllfct_export
double ddm7_nllfct_export(const arma::colvec& alpha, const arma::vec& rt, const arma::ivec& xs, const std::string& type_alpha, const std::string& type_ddm, const int& kmax, const double& delta, bool use_lan);
RcppExport SEXP _nsddm_ddm7_nllfct_export(SEXP alphaSEXP, SEXP rtSEXP, SEXP xsSEXP, SEXP type_alphaSEXP, SEXP type_ddmSEXP, SEXP kmaxSEXP, SEXP deltaSEXP, SEXP use_lanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type rt(rtSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type_alpha(type_alphaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type_ddm(type_ddmSEXP);
    Rcpp::traits::input_parameter< const int& >::type kmax(kmaxSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_lan(use_lanSEXP);
    rcpp_result_gen = Rcpp::wrap(ddm7_nllfct_export(alpha, rt, xs, type_alpha, type_ddm, kmax, delta, use_lan));
    return rcpp_result_gen;
END_RCPP
}
// ddm7_random_llfct_rcpp
double ddm7_random_llfct_rcpp(const arma::colvec& alpha, const arma::vec& rti, const arma::ivec& xsi, const arma::vec& MU, const arma::mat& SIGMA, const std::string& type_alpha, const std::string& type_ddm, const int& kmax, const double& delta, bool use_lan);
RcppExport SEXP _nsddm_ddm7_random_llfct_rcpp(SEXP alphaSEXP, SEXP rtiSEXP, SEXP xsiSEXP, SEXP MUSEXP, SEXP SIGMASEXP, SEXP type_alphaSEXP, SEXP type_ddmSEXP, SEXP kmaxSEXP, SEXP deltaSEXP, SEXP use_lanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type rti(rtiSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type xsi(xsiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type MU(MUSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SIGMA(SIGMASEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type_alpha(type_alphaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type_ddm(type_ddmSEXP);
    Rcpp::traits::input_parameter< const int& >::type kmax(kmaxSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_lan(use_lanSEXP);
    rcpp_result_gen = Rcpp::wrap(ddm7_random_llfct_rcpp(alpha, rti, xsi, MU, SIGMA, type_alpha, type_ddm, kmax, delta, use_lan));
    return rcpp_result_gen;
END_RCPP
}
// ddm7_random_nllfct_rcpp
double ddm7_random_nllfct_rcpp(const arma::colvec& alpha, const arma::vec& rti, const arma::ivec& xsi, const arma::vec& MU, const arma::mat& SIGMA, const std::string& type_alpha, const std::string& type_ddm, const int& kmax, const double& delta, bool use_lan);
RcppExport SEXP _nsddm_ddm7_random_nllfct_rcpp(SEXP alphaSEXP, SEXP rtiSEXP, SEXP xsiSEXP, SEXP MUSEXP, SEXP SIGMASEXP, SEXP type_alphaSEXP, SEXP type_ddmSEXP, SEXP kmaxSEXP, SEXP deltaSEXP, SEXP use_lanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type rti(rtiSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type xsi(xsiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type MU(MUSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SIGMA(SIGMASEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type_alpha(type_alphaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type_ddm(type_ddmSEXP);
    Rcpp::traits::input_parameter< const int& >::type kmax(kmaxSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_lan(use_lanSEXP);
    rcpp_result_gen = Rcpp::wrap(ddm7_random_nllfct_rcpp(alpha, rti, xsi, MU, SIGMA, type_alpha, type_ddm, kmax, delta, use_lan));
    return rcpp_result_gen;
END_RCPP
}
// ddm_agh_gradfct_singleperson_rcpp
Rcpp::List ddm_agh_gradfct_singleperson_rcpp(const arma::vec& typevec, const arma::mat& posmat, const arma::vec& rti, const arma::ivec& xsi, const arma::mat& pts, const arma::vec& wgh, const arma::vec& MU, const arma::mat& L, const arma::mat& SIGMA, const arma::mat& invSIGMA, const std::string& type_alpha, const std::string& type_ddm, const std::string& ddm, const int& kmax, const double& delta, bool use_lan, std::string lan_path);
RcppExport SEXP _nsddm_ddm_agh_gradfct_singleperson_rcpp(SEXP typevecSEXP, SEXP posmatSEXP, SEXP rtiSEXP, SEXP xsiSEXP, SEXP ptsSEXP, SEXP wghSEXP, SEXP MUSEXP, SEXP LSEXP, SEXP SIGMASEXP, SEXP invSIGMASEXP, SEXP type_alphaSEXP, SEXP type_ddmSEXP, SEXP ddmSEXP, SEXP kmaxSEXP, SEXP deltaSEXP, SEXP use_lanSEXP, SEXP lan_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type typevec(typevecSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type posmat(posmatSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type rti(rtiSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type xsi(xsiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type pts(ptsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type wgh(wghSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type MU(MUSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SIGMA(SIGMASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type invSIGMA(invSIGMASEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type_alpha(type_alphaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type_ddm(type_ddmSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type ddm(ddmSEXP);
    Rcpp::traits::input_parameter< const int& >::type kmax(kmaxSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_lan(use_lanSEXP);
    Rcpp::traits::input_parameter< std::string >::type lan_path(lan_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(ddm_agh_gradfct_singleperson_rcpp(typevec, posmat, rti, xsi, pts, wgh, MU, L, SIGMA, invSIGMA, type_alpha, type_ddm, ddm, kmax, delta, use_lan, lan_path));
    return rcpp_result_gen;
END_RCPP
}
// ddm_agh_gradfct_allpersons_rcpp
Rcpp::List ddm_agh_gradfct_allpersons_rcpp(const arma::vec& typevec, const arma::mat& posmat, const arma::vec& rts, const arma::ivec& xs, const arma::imat& info, const int I, const arma::cube& pts_array, const arma::mat& wgh_mat, const arma::vec& MU, const arma::mat& L, const arma::mat& SIGMA, const arma::mat& invSIGMA, const std::string& type_ddm, const std::string& type_alpha, const std::string& ddm, const int& kmax, const double& delta, bool use_lan, std::string lan_path, int n_threads);
RcppExport SEXP _nsddm_ddm_agh_gradfct_allpersons_rcpp(SEXP typevecSEXP, SEXP posmatSEXP, SEXP rtsSEXP, SEXP xsSEXP, SEXP infoSEXP, SEXP ISEXP, SEXP pts_arraySEXP, SEXP wgh_matSEXP, SEXP MUSEXP, SEXP LSEXP, SEXP SIGMASEXP, SEXP invSIGMASEXP, SEXP type_ddmSEXP, SEXP type_alphaSEXP, SEXP ddmSEXP, SEXP kmaxSEXP, SEXP deltaSEXP, SEXP use_lanSEXP, SEXP lan_pathSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type typevec(typevecSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type posmat(posmatSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type rts(rtsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type info(infoSEXP);
    Rcpp::traits::input_parameter< const int >::type I(ISEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type pts_array(pts_arraySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type wgh_mat(wgh_matSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type MU(MUSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SIGMA(SIGMASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type invSIGMA(invSIGMASEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type_ddm(type_ddmSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type_alpha(type_alphaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type ddm(ddmSEXP);
    Rcpp::traits::input_parameter< const int& >::type kmax(kmaxSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_lan(use_lanSEXP);
    Rcpp::traits::input_parameter< std::string >::type lan_path(lan_pathSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(ddm_agh_gradfct_allpersons_rcpp(typevec, posmat, rts, xs, info, I, pts_array, wgh_mat, MU, L, SIGMA, invSIGMA, type_ddm, type_alpha, ddm, kmax, delta, use_lan, lan_path, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// ddm_agh_gradfct_allpersons_rcpp_save
Rcpp::List ddm_agh_gradfct_allpersons_rcpp_save(const arma::vec& typevec, const arma::mat& posmat, const arma::vec& rts, const arma::ivec& xs, const arma::imat& info, const int I, const arma::cube& pts_array, const arma::mat& wgh_mat, const arma::vec& MU, const arma::mat& L, const arma::mat& SIGMA, const arma::mat& invSIGMA, const std::string& type_ddm, const std::string& type_alpha, const std::string& ddm, const int& kmax, const double& delta, bool use_lan, std::string lan_path, int n_threads);
RcppExport SEXP _nsddm_ddm_agh_gradfct_allpersons_rcpp_save(SEXP typevecSEXP, SEXP posmatSEXP, SEXP rtsSEXP, SEXP xsSEXP, SEXP infoSEXP, SEXP ISEXP, SEXP pts_arraySEXP, SEXP wgh_matSEXP, SEXP MUSEXP, SEXP LSEXP, SEXP SIGMASEXP, SEXP invSIGMASEXP, SEXP type_ddmSEXP, SEXP type_alphaSEXP, SEXP ddmSEXP, SEXP kmaxSEXP, SEXP deltaSEXP, SEXP use_lanSEXP, SEXP lan_pathSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type typevec(typevecSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type posmat(posmatSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type rts(rtsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type info(infoSEXP);
    Rcpp::traits::input_parameter< const int >::type I(ISEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type pts_array(pts_arraySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type wgh_mat(wgh_matSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type MU(MUSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SIGMA(SIGMASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type invSIGMA(invSIGMASEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type_ddm(type_ddmSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type type_alpha(type_alphaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type ddm(ddmSEXP);
    Rcpp::traits::input_parameter< const int& >::type kmax(kmaxSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_lan(use_lanSEXP);
    Rcpp::traits::input_parameter< std::string >::type lan_path(lan_pathSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(ddm_agh_gradfct_allpersons_rcpp_save(typevec, posmat, rts, xs, info, I, pts_array, wgh_mat, MU, L, SIGMA, invSIGMA, type_ddm, type_alpha, ddm, kmax, delta, use_lan, lan_path, n_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nsddm_ddm_chain_rcpp", (DL_FUNC) &_nsddm_ddm_chain_rcpp, 32},
    {"_nsddm_ddm4_pdf_export", (DL_FUNC) &_nsddm_ddm4_pdf_export, 10},
    {"_nsddm_ddm7_pdf_export", (DL_FUNC) &_nsddm_ddm7_pdf_export, 12},
    {"_nsddm_lan_load_weights_export", (DL_FUNC) &_nsddm_lan_load_weights_export, 2},
    {"_nsddm_ddm4_lanll_weights_export", (DL_FUNC) &_nsddm_ddm4_lanll_weights_export, 6},
    {"_nsddm_ddm4_lanll_grad_weights_rcpp", (DL_FUNC) &_nsddm_ddm4_lanll_grad_weights_rcpp, 3},
    {"_nsddm_ddm7_lanll_grad_weights_rcpp", (DL_FUNC) &_nsddm_ddm7_lanll_grad_weights_rcpp, 3},
    {"_nsddm_ddm_lan_nllfct_gradient_rcpp", (DL_FUNC) &_nsddm_ddm_lan_nllfct_gradient_rcpp, 7},
    {"_nsddm_ddm4_nllfct_export", (DL_FUNC) &_nsddm_ddm4_nllfct_export, 8},
    {"_nsddm_ddm4_random_llfct_rcpp", (DL_FUNC) &_nsddm_ddm4_random_llfct_rcpp, 10},
    {"_nsddm_ddm4_random_nllfct_rcpp", (DL_FUNC) &_nsddm_ddm4_random_nllfct_rcpp, 10},
    {"_nsddm_ddm7_nllfct_export", (DL_FUNC) &_nsddm_ddm7_nllfct_export, 8},
    {"_nsddm_ddm7_random_llfct_rcpp", (DL_FUNC) &_nsddm_ddm7_random_llfct_rcpp, 10},
    {"_nsddm_ddm7_random_nllfct_rcpp", (DL_FUNC) &_nsddm_ddm7_random_nllfct_rcpp, 10},
    {"_nsddm_ddm_agh_gradfct_singleperson_rcpp", (DL_FUNC) &_nsddm_ddm_agh_gradfct_singleperson_rcpp, 17},
    {"_nsddm_ddm_agh_gradfct_allpersons_rcpp", (DL_FUNC) &_nsddm_ddm_agh_gradfct_allpersons_rcpp, 20},
    {"_nsddm_ddm_agh_gradfct_allpersons_rcpp_save", (DL_FUNC) &_nsddm_ddm_agh_gradfct_allpersons_rcpp_save, 20},
    {NULL, NULL, 0}
};

RcppExport void R_init_nsddm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
